import {useState,useEffect} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {ArrowLeft, ArrowUpRight, Bookmark, Check, ShieldCheck, History, GitBranch, ExternalLink, Eye, EyeOff, FileText, Share2, ChevronRight, Pencil} from 'lucide-react';
import {toast} from 'sonner';
import {api} from '../lib/api';
import {OFFLINE} from '../lib/offline';
import {useSaved} from '../lib/saved';
import {assetUrl} from '../lib/assets';
import {Entity,Claim,Revision,dateLabel,typeNames} from '../types';
import {Button} from '../components/ui/button';
import {EntityCard} from '../components/EntityCard';
import {EvidencePanel} from '../components/EvidencePanel';
import {RevisionDiff} from '../components/RevisionDiff';
export default function EntityDetail(){
  const {slug}=useParams();const [params]=useSearchParams();const version=params.get('versao');
  const [entity,setEntity]=useState<Entity|null>(null),[history,setHistory]=useState<Revision[]>([]),[error,setError]=useState('');
  const [tab,setTab]=useState('ficha'),[evidence,setEvidence]=useState<Claim|null>(null),[spoilers,setSpoilers]=useState(false);
  const {saved,toggle}=useSaved();
  useEffect(()=>{let alive=true;setEntity(null);setError('');setTab('ficha');Promise.all([api<Entity>(`/entities/${slug}${version?`?version=${version}`:''}`),api<Revision[]>(`/entities/${slug}/history`)]).then(([e,h])=>{if(alive){setEntity(e);setHistory(h);document.title=`${e.name} — VI Archive`;}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[slug,version]);
  if(error)return <div className="page-content empty-state"><FileText size={40}/><h1 data-testid="entity-error-title">Página indisponível</h1><p role="alert" data-testid="entity-error">{error}</p><Link to="/encontrar" data-testid="entity-error-back">Voltar ao arquivo</Link></div>;
  if(!entity)return <div className="page-content"><div className="skeleton detail-skeleton" data-testid="entity-loading"/></div>;
  return <div className="page-enter">
    <section className="detail-hero" data-entity={entity.slug}>{entity.image?<img src={assetUrl(entity.image)} alt={entity.name} style={{objectPosition:entity.image_position}}/>:<div className="image-empty detail-hero-empty" aria-hidden="true"><FileText size={56}/></div>}<div className="detail-hero-shade"/><div className="detail-hero-content"><Link to="/encontrar" className="back-link" data-testid="entity-back"><ArrowLeft size={15}/> O arquivo <ChevronRight size={12}/> {typeNames[entity.type]}</Link><div className="detail-title-row"><div><span className="eyebrow">DOSSIÊ / {entity.type.toUpperCase()}</span><h1 data-testid="entity-name">{entity.name}</h1><p data-testid="entity-summary">{entity.summary}</p></div><div className="detail-actions"><Button className={saved.includes(entity.id)?'saved-button':'primary-button'} data-testid="entity-save" onClick={()=>toggle(entity.id)}>{saved.includes(entity.id)?<Check size={17}/>:<Bookmark size={17}/>} {saved.includes(entity.id)?'Guardado':'Guardar'}</Button><Button variant="outline" size="icon" className="share-button" data-testid="entity-share" aria-label={OFFLINE ? 'Copiar referência' : 'Copiar ligação'} onClick={async()=>{try{await navigator.clipboard.writeText(OFFLINE ? `${entity.name} — VI Archive (edição offline)\n${entity.summary}\nID: ${entity.id}` : window.location.href);toast.success(OFFLINE ? 'Referência copiada.' : 'Ligação copiada.');}catch{toast.error('Não foi possível copiar.');}}}><Share2 size={17}/></Button></div></div><div className="detail-meta"><span className="official-tag"><ShieldCheck size={13}/>{entity.label}</span><span>{entity.assertion_count} afirmações documentadas</span><span>Publicação {entity.version}</span><span>{dateLabel(entity.updated_at)}</span></div></div></section>
    <div className="detail-body">
      {version&&<div className="historical-warning" data-testid="historical-warning"><History size={18}/> Está a consultar uma publicação histórica (v{version}). <Link to={`/entidade/${slug}`} data-testid="current-version-link">Ver publicação atual <ArrowUpRight size={14}/></Link></div>}
      <div className="detail-tabs" role="tablist" aria-label="Secções da entidade" onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role=tab]'));const current=tabs.findIndex(button=>button.getAttribute('aria-selected')==='true');const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next]?.click();tabs[next]?.focus();}}>{[{id:'ficha',label:'Ficha e evidências',icon:FileText},{id:'relacoes',label:'Relações',icon:GitBranch},{id:'historico',label:'Histórico',icon:History}].map(({id,label,icon:Icon})=><button key={id} role="tab" id={`dossier-tab-${id}`} aria-controls={`dossier-panel-${id}`} tabIndex={tab===id?0:-1} aria-selected={tab===id} data-testid={`entity-tab-${id}`} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}{id==='relacoes'&&<span>{entity.related?.length}</span>}</button>)}</div>
      {tab==='ficha'&&<div className="entity-detail-grid" role="tabpanel" id="dossier-panel-ficha" aria-labelledby="dossier-tab-ficha"><section><div className="section-heading"><h2>O que sabemos</h2><button className="spoiler-toggle" data-testid="spoiler-toggle" onClick={()=>setSpoilers(!spoilers)} aria-pressed={spoilers}>{spoilers?<Eye size={14}/>:<EyeOff size={14}/>} {spoilers?'Ocultar spoilers':'Mostrar spoilers'}</button></div><div className="assertion-list">{entity.assertions?.map((claim,index)=><div className="assertion-row" data-order={String(index + 1).padStart(2, '0')} key={claim.id} data-testid={`claim-${claim.id}`}><span className="claim-property">{claim.property}</span><div><p className={claim.spoiler&&!spoilers?'spoiler-hidden':''} data-testid={`claim-value-${claim.id}`}>{claim.spoiler&&!spoilers?'Informação narrativa oculta':claim.value}</p><span className="claim-status"><span className="status-dot"/>{claim.origin==='oficial'?'Fonte oficial':claim.origin} <span>·</span> {claim.verification==='pendente'?'Verificação pendente':claim.verification}</span></div><button className="evidence-button" data-testid={`evidence-open-${claim.id}`} onClick={()=>setEvidence(claim)} aria-label={`Ver evidência de ${claim.property}`}><ShieldCheck size={16}/><span>Fonte</span><ArrowUpRight size={13}/></button></div>)}</div><p className="unknown-note" data-testid="unknown-data-note">Informação não documentada permanece desconhecida. A ausência de um dado não significa que seja zero ou que não exista.</p></section><aside className="entity-context"><span className="section-kicker">CONTEXTO DO REGISTO</span><h2>Do anúncio ao arquivo.</h2><dl><dt>Estado da informação</dt><dd>Material oficial pré-lançamento</dd><dt>Aplicabilidade</dt><dd>Sem versão jogável identificada</dd><dt>Identificador estável</dt><dd className="mono" data-testid="entity-stable-id">{entity.id}</dd><dt>Nomes alternativos</dt><dd>{entity.aliases.join(' · ')||'Nenhum registado'}</dd></dl><Link to="/metodologia" data-testid="entity-method-link">Como avaliamos a evidência <ArrowUpRight size={14}/></Link><Link to={`/redacao?entidade=${entity.slug}`} data-testid="suggest-correction">Propor uma revisão <Pencil size={13}/></Link></aside></div>}
      {tab==='relacoes'&&<section className="tab-content" role="tabpanel" id="dossier-panel-relacoes" aria-labelledby="dossier-tab-relacoes"><div className="section-heading"><h2>Ligações documentadas</h2><span>Relações nos dois sentidos</span></div>{entity.related?.length?<div className="entity-grid">{entity.related.map(e=><EntityCard key={e.id} entity={e}/>)}</div>:<div className="empty-state" data-testid="no-relations"><GitBranch size={30}/><h2>Ainda sem relações publicadas.</h2></div>}</section>}
      {tab==='historico'&&<section className="tab-content" role="tabpanel" id="dossier-panel-historico" aria-labelledby="dossier-tab-historico"><div className="section-heading"><h2>Histórico editorial</h2><span>Não representa alterações ao jogo</span></div><div className="revision-list">{history.map((rev,i)=><article className="revision-item" key={rev.id} data-testid={`revision-${rev.version}`}><div className="revision-number">v{rev.version}</div><div className="revision-main"><span className="mono">{dateLabel(rev.created_at)}{i===0?' · PUBLICAÇÃO ATUAL':''}</span><h3>{rev.reason}</h3><p>{rev.author_name} <span>→</span> {rev.reviewer_name}</p>{i<history.length-1&&<RevisionDiff slug={slug!} from={history[i+1].version} to={rev.version}/>}</div><Link to={`/entidade/${slug}?versao=${rev.version}`} data-testid={`view-revision-${rev.version}`}>Consultar <ArrowUpRight size={15}/></Link></article>)}</div></section>}
      {tab==='ficha'&&!!entity.related?.length&&<section className="related-section"><div className="section-heading"><div><span className="section-kicker">O CONHECIMENTO ESTÁ LIGADO</span><h2>Neste mesmo universo</h2></div><button className="text-link" data-testid="show-all-relations" onClick={()=>setTab('relacoes')}>Ver relações <ArrowUpRight size={15}/></button></div><div className="entity-grid">{entity.related.slice(0,4).map(e=><EntityCard key={e.id} entity={e}/>)}</div></section>}
    </div><EvidencePanel claim={evidence} onClose={()=>setEvidence(null)}/>
  </div>;
}