import {useState} from 'react';
import {Link} from 'react-router-dom';
import {BookOpen,Check,ArrowUpRight,ShieldCheck,Scale,Map,ChevronRight,ClipboardList} from 'lucide-react';
import {Checkbox} from '../components/ui/checkbox';
const steps=[{id:'official',title:'Consultar a apresentação oficial',detail:'A informação primária publicada pela Rockstar.',url:'https://www.rockstargames.com/VI',external:true},{id:'people',title:'Conhecer Jason e Lucia',detail:'As pessoas no centro da história de Leonida.',url:'/encontrar?tipo=personagem'},{id:'places',title:'Explorar os locais anunciados',detail:'Vice City, as Keys e os outros destinos documentados.',url:'/encontrar?tipo=local'},{id:'sources',title:'Distinguir origem de verificação',detail:'Os critérios de evidência por trás de cada afirmação.',url:'/metodologia'}];
export default function Resolve(){
  const [done,setDone]=useState<string[]>(()=>{try{const x=JSON.parse(localStorage.getItem('vi-checklist')||'[]');return Array.isArray(x)?x:[];}catch{return[];}});
  const toggle=(id:string)=>{setDone(previous=>{const next=previous.includes(id)?previous.filter(x=>x!==id):[...previous,id];try{localStorage.setItem('vi-checklist',JSON.stringify(next));}catch{}return next;});};
  return <div className="page-content page-enter"><header className="page-heading"><span className="eyebrow">RESOLVER / GUIAS E FERRAMENTAS</span><h1 data-testid="resolve-title">Um bom ponto de partida.</h1><p>Antes de entrar em Leonida, comece pelo que está documentado.</p></header><div className="guide-layout"><section><div className="guide-title"><div><span className="section-kicker">CHECKLIST DE LEITURA</span><h2>Primeiros passos no arquivo</h2></div><span className="progress-count" data-testid="checklist-progress">{done.filter(id=>steps.some(s=>s.id===id)).length} / {steps.length}</span></div><div className="progress-track"><span style={{width:`${done.filter(id=>steps.some(s=>s.id===id)).length/steps.length*100}%`}}/></div><div className="checklist">{steps.map((step,i)=><div className={`checklist-row ${done.includes(step.id)?'done':''}`} key={step.id}><Checkbox checked={done.includes(step.id)} onCheckedChange={()=>toggle(step.id)} data-testid={`checklist-${step.id}`} aria-label={`Concluir: ${step.title}`}/><div><span className="mono">0{i+1}</span><h3>{step.title}</h3><p>{step.detail}</p></div>{step.external?<a href={step.url} target="_blank" rel="noreferrer" data-testid={`checklist-link-${step.id}`} aria-label={step.title}><ArrowUpRight size={20}/></a>:<Link to={step.url} data-testid={`checklist-link-${step.id}`} aria-label={step.title}><ArrowUpRight size={20}/></Link>}</div>)}</div><span className="local-note">Progresso de leitura guardado apenas neste navegador.</span></section><aside className="guide-aside"><ShieldCheck size={29}/><h2>Útil só quando é fiável.</h2><p>Guias de jogo, comparadores e mapas dependem de dados confirmados. Não antecipamos mecânicas nem inventamos trajetos.</p><Link to="/metodologia" data-testid="resolve-method">O nosso compromisso <ArrowUpRight size={14}/></Link></aside></div><section className="tool-status"><div><Scale size={23}/><h3>Comparadores</h3><span className="pending-badge">EVIDÊNCIA EM FALTA</span><p>Ainda não há medições compatíveis publicadas para criar rankings factuais.</p></div><div><Map size={23}/><h3>Mapa interativo</h3><span className="pending-badge">CARTOGRAFIA EM FALTA</span><p>Sem um mapa verificável e direitos de utilização confirmados, não publicamos coordenadas.</p><Link to="/encontrar?tipo=local" data-testid="resolve-locations">Consultar locais documentados <ArrowUpRight size={13}/></Link></div></section></div>;
}