import {useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {Bookmark,ArrowUpRight,Download,Trash2,HardDrive} from 'lucide-react';
import {useSaved} from '../lib/saved';
import {api} from '../lib/api';
import {Entity,SearchResult} from '../types';
import {EntityCard} from '../components/EntityCard';
import {Button} from '../components/ui/button';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '../components/ui/alert-dialog';
export default function Saved(){
  const {saved,clear}=useSaved();const [items,setItems]=useState<Entity[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let active=true;setError('');if(!saved.length){setItems([]);setLoading(false);return;}setLoading(true);const chunks=Array.from({length:Math.ceil(saved.length/48)},(_,i)=>saved.slice(i*48,i*48+48));Promise.all(chunks.map(ids=>api<SearchResult>(`/entities?ids=${encodeURIComponent(ids.join(','))}&limit=48`))).then(results=>active&&setItems(results.flatMap(v=>v.items))).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[saved]);
  const download=()=>{const blob=new Blob([JSON.stringify({archive:'VI Archive',exported_at:new Date().toISOString(),entities:items.map(({id,slug,name})=>({id,slug,name}))},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='vi-archive-guardados.json';a.click();URL.revokeObjectURL(url);};
  return <div className="page-content page-enter"><header className="page-heading"><span className="eyebrow">GUARDAR / O SEU ARQUIVO</span><h1 data-testid="saved-title">Vale a pena voltar.</h1><p>As pessoas e os lugares que quer manter por perto.</p></header><div className="saved-toolbar"><span data-testid="saved-total"><Bookmark size={16}/>{saved.length} entidades guardadas</span><div>{items.length>0&&<><Button variant="outline" data-testid="export-saved" onClick={download}><Download size={15}/>Exportar</Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" data-testid="clear-saved"><Trash2 size={15}/>Limpar</Button></AlertDialogTrigger><AlertDialogContent data-testid="clear-saved-dialog"><AlertDialogHeader><AlertDialogTitle>Limpar os seus guardados?</AlertDialogTitle><AlertDialogDescription>Esta ação remove os favoritos deste navegador. Os conteúdos do arquivo não serão alterados.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel data-testid="cancel-clear-saved">Cancelar</AlertDialogCancel><AlertDialogAction data-testid="confirm-clear-saved" onClick={clear}>Limpar guardados</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>}</div></div>{error&&<p role="alert" data-testid="saved-error">{error}</p>}{loading?<div className="skeleton detail-skeleton"/>:items.length?<div className="entity-grid search-grid">{items.map(item=><EntityCard key={item.id} entity={item}/>)}</div>:<div className="empty-state saved-empty" data-testid="saved-empty"><Bookmark size={42} strokeWidth={1}/><h2>O seu arquivo começa com uma descoberta.</h2><p>Ainda não tem entidades guardadas.</p><Button asChild className="primary-button"><Link to="/encontrar" data-testid="saved-explore">Explorar Leonida <ArrowUpRight size={16}/></Link></Button></div>}<div className="local-note"><HardDrive size={16}/><span data-testid="saved-privacy">Guardado apenas neste navegador. Sem conta, sem histórico de leitura partilhado.</span></div></div>;
}